const VERY_FAST_DURATION = 1;
const FAST_DURATION = 2;
const DEFAUL_DURATION = 3;
const SLOW_DURATION = 4;
const VERY_SLOW_DURATION = 5;

const FONT_SIZE_WIDTH_RATIO = 0.6;
const FONT_SIZE_HEIGHT_RATIO = 1.3529411764705883;
const VERY_SMALL_SCREEN_FONT_SIZE = 12;
const SMALL_SCREEN_FONT_SIZE = 14;
const NORMAL_SCREEN_FONT_SIZE = 16;
const BIG_SCREEN_FONT_SIZE = 18;

export {
    VERY_FAST_DURATION,
    FAST_DURATION,
    DEFAUL_DURATION,
    SLOW_DURATION,
    VERY_SLOW_DURATION,
    FONT_SIZE_WIDTH_RATIO,
    FONT_SIZE_HEIGHT_RATIO,
    VERY_SMALL_SCREEN_FONT_SIZE,
    SMALL_SCREEN_FONT_SIZE,
    NORMAL_SCREEN_FONT_SIZE,
    BIG_SCREEN_FONT_SIZE,
};
